[build]
  command = "npm run build"
  publish = "dist" # Vite ka output folder
  # publish = "build" # React CRA ka output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
